# This is a basic workflow to help you get started with Actions

name: DockerHub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  upload_image:
    
    runs-on: ubuntu-latest
    # needs: test
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Test environment
        run: |
          uname -a 
          cat /etc/debian_version
          ip a 
          docker --version
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rdma_interface_example:latest
      
      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          docker image ls
